//Use Win-1251 encoding
#include "Arduino.h"
#include "font.hpp"
#include "EEPROM.h"//it's better to isolate EEPROM access here with some settings class

const char syl_rus_0[] PROGMEM = "“¿";
const char syl_rus_1[] PROGMEM = "–Œ";
const char syl_rus_2[] PROGMEM = "¿Ã";
const char syl_rus_3[] PROGMEM = "¬≈ƒ";
const char syl_rus_4[] PROGMEM = "Œ“";
const char syl_rus_5[] PROGMEM = "Õ» ";
const char syl_rus_6[] PROGMEM = "Ã¿“";
const char syl_rus_7[] PROGMEM = "ÀŒ¬";
const char syl_rus_8[] PROGMEM = "–”";
const char syl_rus_9[] PROGMEM = "Œ ";
const char syl_rus_10[] PROGMEM = "—”ƒ¿";
const char syl_rus_11[] PROGMEM = "ÀŒ";
const char syl_rus_12[] PROGMEM = "¿ƒ";
const char syl_rus_13[] PROGMEM = "¿Õ“";
const char syl_rus_14[] PROGMEM = "’Œƒ";
const char syl_rus_15[] PROGMEM = "” ";
const char syl_rus_16[] PROGMEM = "«¿";
const char syl_rus_17[] PROGMEM = "–≈«";
const char syl_rus_18[] PROGMEM = "Œƒ";
const char syl_rus_19[] PROGMEM = "“Œ–";
const char syl_rus_20[] PROGMEM = "» ";
const char syl_rus_21[] PROGMEM = "œŒ";
const char syl_rus_22[] PROGMEM = "√¿";
const char syl_rus_23[] PROGMEM = "ƒŒ ";
const char syl_rus_24[] PROGMEM = "¿“";
const char syl_rus_25[] PROGMEM = "¬» ";
const char syl_rus_26[] PROGMEM = "—¿";
const char syl_rus_27[] PROGMEM = "À¿";
const char syl_rus_28[] PROGMEM = "À≈";
const char syl_rus_29[] PROGMEM = "¿—“";
const char syl_rus_30[] PROGMEM = "¿À";
const char syl_rus_31[] PROGMEM = "¿ ";
const char syl_rus_32[] PROGMEM = "ÀŒÃ";
const char syl_rus_33[] PROGMEM = "–Œ√";
const char syl_rus_34[] PROGMEM = "ƒ≈À";
const char syl_rus_35[] PROGMEM = "“» ";
const char syl_rus_36[] PROGMEM = "—ŒÕ";
const char syl_rus_37[] PROGMEM = "“≈À";
const char syl_rus_38[] PROGMEM = "»“";
const char syl_rus_39[] PROGMEM = "¿«";
const char syl_rus_40[] PROGMEM = "¬≈ ";
const char syl_rus_41[] PROGMEM = "À»";
const char syl_rus_42[] PROGMEM = " Œ";
const char syl_rus_43[] PROGMEM = "–¿";
const char syl_rus_44[] PROGMEM = " ≈";
const char syl_rus_45[] PROGMEM = "◊¿";
const char syl_rus_46[] PROGMEM = "œ¿Õ";
const char syl_rus_47[] PROGMEM = "¡ŒÀ";
const char syl_rus_48[] PROGMEM = "Ã≈“–";
const char syl_rus_49[] PROGMEM = " »Õ";
const char syl_rus_50[] PROGMEM = "¿—";
const char syl_rus_51[] PROGMEM = "”«";
const char syl_rus_52[] PROGMEM = "¿–";
const char syl_rus_53[] PROGMEM = "¬Œ";
const char syl_rus_54[] PROGMEM = " ¿";
const char syl_rus_55[] PROGMEM = "≈¬";
const char syl_rus_56[] PROGMEM = "Ã≈“";
const char syl_rus_57[] PROGMEM = "ŒÕ";
const char syl_rus_58[] PROGMEM = "¬Œƒ";
const char syl_rus_59[] PROGMEM = "¡¿";
const char syl_rus_60[] PROGMEM = "¿ “";
const char syl_rus_61[] PROGMEM = "”Õ";
const char syl_rus_62[] PROGMEM = "»À";
const char syl_rus_63[] PROGMEM = "¬¿–";
const char syl_rus_64[] PROGMEM = "»«Ã";
const char syl_rus_65[] PROGMEM = "”¡";
const char syl_rus_66[] PROGMEM = "Ã¿";
const char syl_rus_67[] PROGMEM = "ÃŒ";
const char syl_rus_68[] PROGMEM = "À¿—“";
const char syl_rus_69[] PROGMEM = "ÀŒ√";
const char syl_rus_70[] PROGMEM = "–ŒÃ";
const char syl_rus_71[] PROGMEM = "ƒ»";
const char syl_rus_72[] PROGMEM = "¬¿";
const char syl_rus_73[] PROGMEM = " Œœ";
const char syl_rus_74[] PROGMEM = "–Œƒ";
const char syl_rus_75[] PROGMEM = "¬Œ«";
const char syl_rus_76[] PROGMEM = "œ¿";
const char syl_rus_77[] PROGMEM = "–¿Õ";
const char syl_rus_78[] PROGMEM = "Õ≈";
const char syl_rus_79[] PROGMEM = "Œ–";
const char syl_rus_80[] PROGMEM = "»Õ";
const char syl_rus_81[] PROGMEM = "’Œ";
const char syl_rus_82[] PROGMEM = "»Õ“";
const char syl_rus_83[] PROGMEM = "’Œ«";
const char syl_rus_84[] PROGMEM = "Õ¿";
const char syl_rus_85[] PROGMEM = "Ã≈–";
const char syl_rus_86[] PROGMEM = "Ã¿—";
const char syl_rus_87[] PROGMEM = "”—";
const char syl_rus_88[] PROGMEM = "∆”";
const char syl_rus_89[] PROGMEM = "œ»“";
const char syl_rus_90[] PROGMEM = " ŒÀ";
const char syl_rus_91[] PROGMEM = "»—“";
const char syl_rus_92[] PROGMEM = " »";
const char syl_rus_93[] PROGMEM = "—Œ";
const char syl_rus_94[] PROGMEM = "Õ»";
const char syl_rus_95[] PROGMEM = "ŒÃ";
const char syl_rus_96[] PROGMEM = "‘ŒÕ";
const char syl_rus_97[] PROGMEM = "“»";
const char syl_rus_98[] PROGMEM = "ƒ» ";
const char syl_rus_99[] PROGMEM = "“≈";
const char syl_rus_100[] PROGMEM = "Àﬁ";
const char syl_rus_101[] PROGMEM = "ƒ¿";
const char syl_rus_102[] PROGMEM = "Œ¬";
const char syl_rus_103[] PROGMEM = "¿Õ";
const char syl_rus_104[] PROGMEM = "“Œ";
const char syl_rus_105[] PROGMEM = "ÕŒ";
const char syl_rus_106[] PROGMEM = "ÀŒ—";
const char syl_rus_107[] PROGMEM = "Ã”";
const char syl_rus_108[] PROGMEM = "Œ—“";
const char *const syl_rus_table[] PROGMEM = {syl_rus_0, syl_rus_1, syl_rus_2, syl_rus_3, syl_rus_4, syl_rus_5, syl_rus_6, syl_rus_7, syl_rus_8, syl_rus_9, syl_rus_10, syl_rus_11, syl_rus_12, syl_rus_13, syl_rus_14, syl_rus_15, syl_rus_16, syl_rus_17, syl_rus_18, syl_rus_19, syl_rus_20, syl_rus_21, syl_rus_22, syl_rus_23, syl_rus_24, syl_rus_25, syl_rus_26, syl_rus_27, syl_rus_28, syl_rus_29, syl_rus_30, syl_rus_31, syl_rus_32, syl_rus_33, syl_rus_34, syl_rus_35, syl_rus_36, syl_rus_37, syl_rus_38, syl_rus_39, syl_rus_40, syl_rus_41, syl_rus_42, syl_rus_43, syl_rus_44, syl_rus_45, syl_rus_46, syl_rus_47, syl_rus_48, syl_rus_49, syl_rus_50, syl_rus_51, syl_rus_52, syl_rus_53, syl_rus_54, syl_rus_55, syl_rus_56, syl_rus_57, syl_rus_58, syl_rus_59, syl_rus_60, syl_rus_61, syl_rus_62, syl_rus_63, syl_rus_64, syl_rus_65, syl_rus_66, syl_rus_67, syl_rus_68, syl_rus_69, syl_rus_70, syl_rus_71, syl_rus_72, syl_rus_73, syl_rus_74, syl_rus_75, syl_rus_76, syl_rus_77, syl_rus_78, syl_rus_79, syl_rus_80, syl_rus_81, syl_rus_82, syl_rus_83, syl_rus_84, syl_rus_85, syl_rus_86, syl_rus_87, syl_rus_88, syl_rus_89, syl_rus_90, syl_rus_91, syl_rus_92, syl_rus_93, syl_rus_94, syl_rus_95, syl_rus_96, syl_rus_97, syl_rus_98, syl_rus_99, syl_rus_100, syl_rus_101, syl_rus_102, syl_rus_103, syl_rus_104, syl_rus_105, syl_rus_106, syl_rus_107, syl_rus_108};

const char syl_eng_0[] PROGMEM = "TI";
const char syl_eng_1[] PROGMEM = "IN";
const char syl_eng_2[] PROGMEM = "RE";
const char syl_eng_3[] PROGMEM = "EN";
const char syl_eng_4[] PROGMEM = "AT";
const char syl_eng_5[] PROGMEM = "IO";
const char syl_eng_6[] PROGMEM = "ER";
const char syl_eng_7[] PROGMEM = "CO";
const char syl_eng_8[] PROGMEM = "ION";
const char syl_eng_9[] PROGMEM = "TE";
const char syl_eng_10[] PROGMEM = "RA";
const char syl_eng_11[] PROGMEM = "AN";
const char syl_eng_12[] PROGMEM = "ST";
const char syl_eng_13[] PROGMEM = "EA";
const char syl_eng_14[] PROGMEM = "AR";
const char syl_eng_15[] PROGMEM = "ES";
const char syl_eng_16[] PROGMEM = "ON";
const char syl_eng_17[] PROGMEM = "RI";
const char syl_eng_18[] PROGMEM = "OR";
const char syl_eng_19[] PROGMEM = "TIO";
const char syl_eng_20[] PROGMEM = "SI";
const char syl_eng_21[] PROGMEM = "ENT";
const char syl_eng_22[] PROGMEM = "DE";
const char syl_eng_23[] PROGMEM = "IS";
const char syl_eng_24[] PROGMEM = "IT";
const char syl_eng_25[] PROGMEM = "RO";
const char syl_eng_26[] PROGMEM = "LI";
const char syl_eng_27[] PROGMEM = "IC";
const char syl_eng_28[] PROGMEM = "NT";
const char syl_eng_29[] PROGMEM = "PR";
const char syl_eng_30[] PROGMEM = "OU";
const char syl_eng_31[] PROGMEM = "ME";
const char syl_eng_32[] PROGMEM = "EL";
const char syl_eng_33[] PROGMEM = "AL";
const char syl_eng_34[] PROGMEM = "TA";
const char syl_eng_35[] PROGMEM = "TR";
const char syl_eng_36[] PROGMEM = "SE";
const char syl_eng_37[] PROGMEM = "LE";
const char syl_eng_38[] PROGMEM = "CA";
const char syl_eng_39[] PROGMEM = "EC";
const char syl_eng_40[] PROGMEM = "HE";
const char syl_eng_41[] PROGMEM = "DI";
const char syl_eng_42[] PROGMEM = "LA";
const char syl_eng_43[] PROGMEM = "VE";
const char syl_eng_44[] PROGMEM = "NC";
const char syl_eng_45[] PROGMEM = "ING";
const char syl_eng_46[] PROGMEM = "UR";
const char syl_eng_47[] PROGMEM = "AC";
const char syl_eng_48[] PROGMEM = "PO";
const char syl_eng_49[] PROGMEM = "ATI";
const char syl_eng_50[] PROGMEM = "AS";
const char syl_eng_51[] PROGMEM = "TH";
const char syl_eng_52[] PROGMEM = "MA";
const char syl_eng_53[] PROGMEM = "PE";
const char syl_eng_54[] PROGMEM = "NE";
const char syl_eng_55[] PROGMEM = "TER";
const char syl_eng_56[] PROGMEM = "OM";
const char syl_eng_57[] PROGMEM = "HO";
const char syl_eng_58[] PROGMEM = "ATE";
const char syl_eng_59[] PROGMEM = "TO";
const char syl_eng_60[] PROGMEM = "NA";
const char syl_eng_61[] PROGMEM = "PA";
const char syl_eng_62[] PROGMEM = "LO";
const char syl_eng_63[] PROGMEM = "UN";
const char syl_eng_64[] PROGMEM = "SU";
const char syl_eng_65[] PROGMEM = "AI";
const char syl_eng_66[] PROGMEM = "NI";
const char syl_eng_67[] PROGMEM = "HI";
const char syl_eng_68[] PROGMEM = "IV";
const char syl_eng_69[] PROGMEM = "NS";
const char syl_eng_70[] PROGMEM = "CON";
const char syl_eng_71[] PROGMEM = "OL";
const char syl_eng_72[] PROGMEM = "EM";
const char syl_eng_73[] PROGMEM = "CT";
const char syl_eng_74[] PROGMEM = "LL";
const char syl_eng_75[] PROGMEM = "MI";
const char syl_eng_76[] PROGMEM = "IL";
const char syl_eng_77[] PROGMEM = "CI";
const char syl_eng_78[] PROGMEM = "CH";
const char syl_eng_79[] PROGMEM = "VI";
const char syl_eng_80[] PROGMEM = "SS";
const char syl_eng_81[] PROGMEM = "MO";
const char syl_eng_82[] PROGMEM = "HA";
const char syl_eng_83[] PROGMEM = "SO";
const char syl_eng_84[] PROGMEM = "US";
const char syl_eng_85[] PROGMEM = "MP";
const char syl_eng_86[] PROGMEM = "FI";
const char syl_eng_87[] PROGMEM = "NCE";
const char syl_eng_88[] PROGMEM = "RES";
const char syl_eng_89[] PROGMEM = "IG";
const char syl_eng_90[] PROGMEM = "ND";
const char syl_eng_91[] PROGMEM = "ET";
const char syl_eng_92[] PROGMEM = "RT";
const char syl_eng_93[] PROGMEM = "AD";
const char syl_eng_94[] PROGMEM = "PL";
const char syl_eng_95[] PROGMEM = "MEN";
const char syl_eng_96[] PROGMEM = "CE";
const char syl_eng_97[] PROGMEM = "IVE";
const char syl_eng_98[] PROGMEM = "IA";
const char syl_eng_99[] PROGMEM = "ESS";
const char syl_eng_100[] PROGMEM = "OS";
const char syl_eng_101[] PROGMEM = "VER";
const char syl_eng_102[] PROGMEM = "IR";
const char syl_eng_103[] PROGMEM = "IM";
const char syl_eng_104[] PROGMEM = "OT";
const char syl_eng_105[] PROGMEM = "EX";
const char syl_eng_106[] PROGMEM = "TU";
const char syl_eng_107[] PROGMEM = "ALL";
const char syl_eng_108[] PROGMEM = "EE";
const char *const syl_eng_table[] PROGMEM = { syl_eng_0,syl_eng_1,syl_eng_2,syl_eng_3,syl_eng_4,syl_eng_5,syl_eng_6,syl_eng_7,syl_eng_8,syl_eng_9,syl_eng_10,syl_eng_11,syl_eng_12,syl_eng_13,syl_eng_14,syl_eng_15,syl_eng_16,syl_eng_17,syl_eng_18,syl_eng_19,syl_eng_20,syl_eng_21,syl_eng_22,syl_eng_23,syl_eng_24,syl_eng_25,syl_eng_26,syl_eng_27,syl_eng_28,syl_eng_29,syl_eng_30,syl_eng_31,syl_eng_32,syl_eng_33,syl_eng_34,syl_eng_35,syl_eng_36,syl_eng_37,syl_eng_38,syl_eng_39,syl_eng_40,syl_eng_41,syl_eng_42,syl_eng_43,syl_eng_44,syl_eng_45,syl_eng_46,syl_eng_47,syl_eng_48,syl_eng_49,syl_eng_50,syl_eng_51,syl_eng_52,syl_eng_53,syl_eng_54,syl_eng_55,syl_eng_56,syl_eng_57,syl_eng_58,syl_eng_59,syl_eng_60,syl_eng_61,syl_eng_62,syl_eng_63,syl_eng_64,syl_eng_65,syl_eng_66,syl_eng_67,syl_eng_68,syl_eng_69,syl_eng_70,syl_eng_71,syl_eng_72,syl_eng_73,syl_eng_74,syl_eng_75,syl_eng_76,syl_eng_77,syl_eng_78,syl_eng_79,syl_eng_80,syl_eng_81,syl_eng_82,syl_eng_83,syl_eng_84,syl_eng_85,syl_eng_86,syl_eng_87,syl_eng_88,syl_eng_89,syl_eng_90,syl_eng_91,syl_eng_92,syl_eng_93,syl_eng_94,syl_eng_95,syl_eng_96,syl_eng_97,syl_eng_98,syl_eng_99,syl_eng_100,syl_eng_101,syl_eng_102,syl_eng_103,syl_eng_104,syl_eng_105,syl_eng_106,syl_eng_107,syl_eng_108 };

byte usedSyls[150];
byte usedSylsCount = 0;

void drawRandomSyllable() {
    char buf[10];
    char *cp;
    const char *const *syl_table = (EEPROM.read(0)) ? syl_rus_table : syl_eng_table;
    int sylind;
    int maxsylind = ((EEPROM.read(0)) ? sizeof(syl_rus_table) : sizeof(syl_eng_table)) /sizeof(char*);
    do {
        sylind = random(maxsylind);
        //Serial.print('!');Serial.print(sylind);Serial.print(' ');
        byte i=0;
        while (i<usedSylsCount) {
            if (usedSyls[i] == sylind) break;
            i++;
        }
        if (i >= usedSylsCount) break;
    } while (true);
    Serial.print(sylind);Serial.print(' ');Serial.println(usedSylsCount);
    usedSyls[usedSylsCount-1] = sylind;
    usedSylsCount++;
    if (usedSylsCount >= maxsylind) usedSylsCount = 0;//reset once all played

    switch ( EEPROM.read(3) ? random(3) : 100) {
        case 0:
            //ellipsis at the end
            strcpy_P(buf, (char *)pgm_read_word(&(syl_table[sylind])));
            cp = buf + strlen(buf);
            *(cp++) = 32;
            *(cp++) = 0;
            break;
        case 1:
            //ellipsis at the beginning
            buf[0] = 32;
            strcpy_P(buf+1, (char *)pgm_read_word(&(syl_table[sylind])));
            break;
        case 2:
            //ellipsis at the beginning and at the end
            buf[0] = 32;
            strcpy_P(buf+1, (char *)pgm_read_word(&(syl_table[sylind])));
            cp = buf + strlen(buf);
            *(cp++) = 32;
            *(cp++) = 0;
            break;
        default:
            //no syllable limiaations
            strcpy_P(buf, (char *)pgm_read_word(&(syl_table[sylind])));
            cp = buf + strlen(buf);
            *(cp++) = 0;
            break;
    }

    drawSyllable(buf);
}